# Generated by Django 4.2.2 on 2023-06-08 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.school'),
        ),
    ]
